title: Dom Events
description: >
  Domain Object Model Related and Unrelated Blog Posts
base_url: ""
url: "https://dom.events"
twitter_username: rboudinot
github_username:  selfup
linkedin_username: regisboudinot

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - main.go
  